language: node_js

node_js:
  - "0.11"

env:
  global:
    secure: Jc9tSi/yf5qy1Bz0NipXxixXFYMgksorzHReDLGoeSRGG/5aCO2Py1/SQko6Y6YzR0fvuByWXFM8T8Ob0+soeC26CnLygARm50h4Px5vv9iW0RUd0jkmMqMz67fIrAOptfp1lbHe2m9Xe91XhBDTcF6HhdXXKc71y5WsRAawoPA=

before_install:
  - cp travis-ci.sh $HOME/

before_script:
  - $HOME/travis-ci.sh before-script

script:
  - $HOME/travis-ci.sh script

after_script:
  - $HOME/travis-ci.sh after-script

after_success:
  - $HOME/travis-ci.sh after-success

cache:
  directories:
    - node_modules

notifications:
  slack:
    rooms:
      - kalamuna:dP7cYTtQ5mOBCp9cpyHHnUYN#kalabox
  irc:
    - "chat.freenode.net#kalabox"
  email:
    recipients:
      - mike@kalamuna.com
      - alec@kalamuna.com
      - coder1@gmail.com
    on_success: always
